#!/usr/bin/env python
# encoding: utf-8

import os


def build_osx_app():
  """This is a setup.py script generated by py2applet

  Usage:
      python setup.py py2app
  """
  from setuptools import setup

  APP = ['NoTagApp.py']
  DATA_FILES = []
  OPTIONS = {'argv_emulation': True,
              'iconfile': 'resource/NoTag.icns',
              'optimize': True}

  setup(
    app=APP,
    name='NoTag',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
  )


def build_win_app():
  """build application for windows"""
  pass

if __name__ == '__main__':
  if os.sys.platform == 'darwin':
    build_osx_app()
  elif os.sys.platform == "win32":
    build_win_app()
